### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by joaocasr** [joaocasr/ENGWEB2023-Projeto#1]
- [X] 1. resolver comunicacao interface-autenticacao
- [x] 2. operacoes de adicao e remocao de rua (atualizacao das ruas relacionadas)
- [X] 3. adicionar funcionalidade de postar comentarios em ruas
